name: eval

model:
  name: simclr
  backbone: resnet50

dataset:
  name: stl10
  image_size: 64
  num_workers: 8

eval: # linear evaluation, False will turn off automatic evaluation after training
  optimizer:
    name: sgd
    weight_decay: 0
    momentum: 0.9
  warmup_lr: 0
  warmup_epochs: 0
  base_lr: 30
  final_lr: 0
  batch_size: 128
  num_epochs: 100
  num_classes: 10
  linear_interval: 500

seed: null
